apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::<ACCOUNT_ID>:user/<YOUR_IAM_USERNAME>
      username: <YOUR_IAM_USERNAME>
      groups:
        - my-viewer


